
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD GET IDENTIFIER NUMBER PRINT SET STRINGstatement : PRINT STRINGstatement : ADD NUMBER NUMBERstatement : SET IDENTIFIER NUMBERstatement : GET IDENTIFIER'
    
_lr_action_items = {'PRINT':([0,],[2,]),'ADD':([0,],[3,]),'SET':([0,],[4,]),'GET':([0,],[5,]),'$end':([1,6,9,10,11,],[0,-1,-4,-2,-3,]),'STRING':([2,],[6,]),'NUMBER':([3,7,8,],[7,10,11,]),'IDENTIFIER':([4,5,],[8,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINT STRING','statement',2,'p_statement_print','KLang.py',32),
  ('statement -> ADD NUMBER NUMBER','statement',3,'p_statement_add','KLang.py',36),
  ('statement -> SET IDENTIFIER NUMBER','statement',3,'p_statement_set','KLang.py',40),
  ('statement -> GET IDENTIFIER','statement',2,'p_statement_get','KLang.py',44),
]
